#!/usr/bin/env bash
# Publish records to kafka topic
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
curl http://localhost:8080/kafka/produce
